book-django-4-by-example/mysite/blog/urls.py
from django.urls import path
from blog import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

book-django-4-by-example/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

book-django-4-by-example/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='published')
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")

    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published_manager = PublishedManager()

    class Meta:
        ordering = ['-published']
        indexes = [models.Index(fields=['-published'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.published.year, self.published.month, self.published.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

book-django-4-by-example/mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

book-django-4-by-example/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from blog.forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count


class PostListView(ListView):
    queryset = Post.published_manager.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    posts_list = Post.published_manager.all()
    page_number = request.GET.get('page', 1)
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts_list = posts_list.filter(tags__in=[tag])

    paginator = Paginator(posts_list, 3)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post, published__year=year,
                             published__month=month,
                             published__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published_manager.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} from {cd['name']} at {post_url}, {cd['comments']}"
            send_mail(subject, message, 'admin@example.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})

book-django-4-by-example/mysite/blog/templates/blog/base.html
{% load blog_tags %}{% load static %}<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
	{% block content %}
	{% endblock %}
</div>
<div id="sidebar">
	<h2>My blog</h2>
	<p>This is my blog.</p>
	I've written {% total_posts %} posts so far.
	<p>
		<a href="{% url "blog:post_feed" %}">
			Subscribe to my RSS feed
		</a>
	</p>
	<h3>Latest posts</h3>
	{% show_latest_posts 3 %}
	<h3>Most commented posts</h3>
	{% get_most_commented_posts as most_commented_posts %}
	<ul>
		{% for post in most_commented_posts %}
			<li>
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			</li>
		{% endfor %}
	</ul>
</div>
</body>
</html>

book-django-4-by-example/mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

book-django-4-by-example/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
	<h1>{{ post.title }}</h1>
	<p class="date">
		Published {{ post.published }} by {{ post.author }}
	</p>
	{{ post.body|markdown }}
	<p>Tags: {{ post.tags.all|join:", " }}</p>
	<p>
		<a href="{% url "blog:post_share" post.id %}">
			Share this post
		</a>
	</p>

	<h2>Similar posts</h2>
	{% for post in similar_posts %}
		<p>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</p>
	{% empty %}
		There are no similar posts yet.
	{% endfor %}

	{% with comments.count as total_comments %}
		<h2>
			{{ total_comments }} comment{{ total_comments|pluralize }}
		</h2>
	{% endwith %}
	{% for comment in comments %}
		<div class="comment">
			<p class="info">
				Comment {{ forloop.counter }} by {{ comment.name }}
				{{ comment.created }}
			</p>
			{{ comment.body|linebreaks }}
		</div>
	{% empty %}
		<p>There are no comments.</p>
	{% endfor %}
	{% include "blog/post/includes/comment_form.html" %}
{% endblock %}

book-django-4-by-example/mysite/blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
  {{ form.as_p }}
  {% csrf_token %}
  <p><input type="submit" value="Add comment"></p>
</form>

book-django-4-by-example/mysite/blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

book-django-4-by-example/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}
{% block content %}
	<h1>My Blog</h1>
	{% if tag %}
		<h2>Posts tagged with "{{ tag.name }}"</h2>
	{% endif %}
	{% for post in posts %}
		<h2>
			<a href="{{ post.get_absolute_url }}">
				{{ post.title }}
			</a>
		</h2>
		<p class="tags">
			Tags:
			{% for tag in post.tags.all %}
				<a href="{% url "blog:post_list_by_tag" tag.slug %}">
					{{ tag.name }}
				</a>
				{% if not forloop.last %}, {% endif %}
			{% endfor %}
		</p>
		<p class="date">
			Published {{ post.published }} by {{ post.author }}
		</p>
		{{ post.body|markdown|truncatewords_html:30 }}
	{% endfor %}
	{% include "pagination.html" with page=posts %}
{% endblock %}

book-django-4-by-example/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
	{% if sent %}
		<h1>E-mail successfully sent</h1>
		<p>
			"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
		</p>
	{% else %}
		<h1>Share "{{ post.title }}" by e-mail</h1>
		<form method="post">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Send e-mail">
		</form>
	{% endif %}
{% endblock %}

book-django-4-by-example/mysite/blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>